backend:
  name: git-gateway
  branch: master # Branch to update (optional; defaults to master)
publish_mode: editorial_workflow

media_folder: "src/assets" # Media files will be stored in the repo under static/images/uploads
public_folder: "/assets" # The src attribute for uploaded media will begin with /images/uploads

collections:
  - name: "blog" # Used in routes, e.g., /admin/collections/blogs
    label: "Blog" # Used in the UI
    folder: "src/pages/blog" # The path to the folder where the documents are stored
    create: true # Allow users to create new documents in this collection
    slug: "{{slug}}" # Filename template, e.g., YYYY-MM-DD-title.md
    fields: # The fields for each document, usually in front matter
      - {label: "Layout", name: "layout", widget: "hidden", default: "../../layouts/BlogPostLayout.astro"}
      - {label: "Author Name", name: "authorName", widget: "string", hint: "Điền bút danh của bạn vào đây nha"}
      - {label: "Author Avatar", name: "authorAvatar", widget: "image"}
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Slug", name: "slug", widget: "string", hint: "Dùng để tạo được dẫn cho bài viết, cần phải unique. Lấy tên của của bài blog, biến các chữ cái in hoa thành viết thường rồi cho dấu - vào giữa các chữ, ví dụ: blog-who-we-are"}
      - {label: "Tag", name: "tag", widget: "select", options: ["Blog", "News"]}
      - {label: "Minutes to read", name: "minutes", widget: "string", hint: "Ước lượng thời gian để đọc, không cần quá chính xác"}
      - {label: "Publish Date", name: "date", widget: "datetime", hint: "Cái này sẽ là tự động, không cần phải điền gì"}
      - {label: "Featured Image", name: "thumbnail", widget: "image", hint: "Có thể copy link ảnh hoặc upload ảnh lên database, ưu tiên phương án thứ nhất hơn"}
      - {label: "Body", name: "body", widget: "markdown"}
  - name: "author"
  - label: "Author"
  - folder: "src/pages/blog/author"
  - create: true
  - slug: "{{name}}"
  - fields:
      - {label: "Name", name: "name", widget: "string"}
      - {label: "Avatar", name: "avatar", widget: "image"}